### PR TITLE
chore(jenkins): updated jenkins slave to the latest version

### PR DESCRIPTION
**Pull request by edewit**
Tested with https://github.com/edewit/fabric8-pipeline-library/tree/snapshot-test

### CODE REVIEW

**Comment by jaseemabid** [comment]
@edewit Looks like you are referring to the image built at https://github.com/fabric8-jenkins/jenkins-openshift-base/commit/54e55b7e765e6e3532dd27a28bed40127262399b and your goal is to update the oc binary. Testing would involve at the minimum running at least one quick start end to end with this version of the library and making sure it gets deployed. I hope you did that already. 

1. This is interesting, because the previous version was pointing to `0.0.1`. I cannot find such a tag at  https://github.com/fabric8-jenkins/jenkins-openshift-base, so what version were we running in prod so far @rupalibehera @sthaha @chmouel ? 

2. @sthaha, there are a few patches by you after this, you might wanna test them and update them here as well? 

3. @rupalibehera, one of your critical fixes (plugin copying) is newer than this patch, so how did we get that into production without updating here? Is this information duplicated in tenant-jenkins repository as well? 

I'm confused! :confused:

**Comment by edewit** [comment]
@jaseemabid yes tested this for a couple of days

**Comment by jaseemabid** [comment]
Docker hub says `0.0.1` is 171 MB and was pushed `a year ago`. 

https://hub.docker.com/r/fabric8/jenkins-slave-base-centos7/tags/

**Comment by quintesse** [comment]
Any progress on this @jaseemabid ? This is blocking progress on our end.

**Comment by jaseemabid** [comment]
@chmouel @rupalibehera @sthaha I'm happy to merge this if there are no concerns from you folks. This LGTM.

**Comment by chmouel** [comment]
I am not seeing where is the tag v54e55b7 in https://hub.docker.com/r/fabric8/jenkins-slave-base-centos7/tags/ am I missing something ?

**Comment by rupalibehera** [comment]
https://hub.docker.com/r/fabric8/jenkins-slave-base-centos7/tags/ I can see the tag

**Pull request merged**
