### PR TITLE
Modified logic to create dependencies #4361

### PR DESCRIPTION
**Pull request by yzainee**
The previous command was not working as expected in cases which had multi maven modules.

Resolves: openshiftio/openshift.io#4361

### CODE REVIEW

**Comment by yzainee** [comment]
Build logs : https://jenkins.prod-preview.openshift.io/job/abs51295/job/maven-simple/job/master/7/console

**Comment by yzainee** [comment]
@bartoszmajsak 
We needed the dependencies which the user is using during the runtime. Its used later to find out the CVEs associated to any of them
I didnt quite get the question on the overhead part. If you are asking how much extra time it takes for build, i think @piyush1594 and @hrishin had already documented it last time
For the 3rd question, in the 1st command it takes only the direct depedencies, whereas in the 2nd it takes in both. The reason is that if you see the output, its doesnt say which is direct/transitive in the combined file. Hence we make use the 1st file to get a diff and find out the transitive and direct respectively

**Comment by bartoszmajsak** [comment]
@yzainee 

> We needed the dependencies which the user is using during the runtime. Its used later to find out the CVEs associated to any of them

In that case don't you also need `provided` and presumably `system` dependencies next to `compile` and `runtime`? These are also used when the app runs (`system` scope is deprecated but still could be used in some cases with proprietary solutions)

> I didnt quite get the question on the overhead part. If you are asking how much extra time it takes for build, i think @piyush1594 and @hrishin had already documented it last time

In this PR goal has changed from `resolve` to `collect` so it has different behaviour. Did you measure it against some real-world projects?

> For the 3rd question, in the 1st command it takes only the direct depedencies, whereas in the 2nd it takes in both. The reason is that if you see the output, its doesnt say which is direct/transitive in the combined file. Hence we make use the 1st file to get a diff and find out the transitive and direct respectively

Thanks for the explanation. I am also curious of why you need that distinction.

**Comment by yzainee** [comment]
@bartoszmajsak 
Yes I have also added a build log in the PR. However, the measurement in terms if time is not something which is constant.
Why distinction -> Because we need to notify the user accordingly for the associated CVEs.
For your 1st point, i will get back to you but as far as i know, the scope says runtime.

**Comment by abs51295** [comment]
@sthaha so we saw failures for this command where the artifact jars are hosted on a private server and aren't downloadable without credentials. So, we found this command that relies only on pom files to generate the dependency tree. Have a look here: https://maven.apache.org/plugins/maven-dependency-plugin/collect-mojo.html.

**Comment by bartoszmajsak** [comment]
@abs51295 to my understanding `provided` means 

> don't make it part of my bundle (e.g. WAR), because I know my **runtime** provides them. I still need them on my classpath though, b/c I program against them (could be API, most of the cases, but not necessarily in all). 

So you are still using it in the runtime while running your app. If there are vulnerabilities it would be worth to know about those too IMHO.

**Comment by abs51295** [comment]
Yes @bartoszmajsak I do understand that as well. But, what's provided at runtime might differ from what's mentioned in pom, and hence we were skeptical about how that will actually be helpful to the end user since that can result in false positives.

**Comment by bartoszmajsak** [comment]
Fair enough @abs51295. That brings a follow-up question - do we scan runtimes too?

**Comment by abs51295** [comment]
> Fair enough @abs51295. That brings a follow-up question - do we scan runtimes too?

No we deal with only application level dependencies.

**Comment by sthaha** [comment]
@yzainee 

Could you please pastebin/upload the logs. We won't be able to access the console logs of your jenkins.

2. The commit message need to include the details in the conversations above 
e.g. https://github.com/fabric8io/fabric8-pipeline-library/pull/432#issuecomment-425037769 is crucial info

which the commit message below does not provide.
```
Modified logic to create dependencies #4361

The previous command was not working as expected in cases which had multi maven modules.
```

**Comment by yzainee** [comment]
@sthaha https://paste.centos.org/view/64f140aa

**Comment by sthaha** [comment]
> @sthaha https://paste.centos.org/view/64f140aa

@yzainee are these "WARNINGS" https://paste.centos.org/view/64f140aa#L243-L248 expected?

**Comment by abs51295** [comment]
@sthaha it's expected because in the user's pom it's missing version for those plugins: https://github.com/abs51295/maven-simple/blob/master/pom.xml#L40-L64

**Pull request merged**
