### PR TITLE
[WIP] Add check to see if content repository is reachable

### PR DESCRIPTION
**Pull request by kishansagathiya**

### CODE REVIEW

**Comment by chmouel** [comment]
looks fine by me (althouh i don't know exactly how those http function works), can you please do the following tests : 

- Run it with content-repository up and see if it builds and store the artifact in the content-repo
- Run it with the content-repository down (oc scale --replicas 0 content-repository) and see if it disables it properly

**Comment by kishansagathiya** [comment]
> see if it disables it properly

What do you mean by this?

**Comment by chmouel** [comment]
basically see if maven don't try to deploy to content-repository and error when it's not avail

**Comment by kishansagathiya** [comment]
@chmouel Tried the second scenario
It stored artifacts in content repo
```
bash-4.2$ pwd
/var/www/html/content/repositories/staging/io/openshift/booster/app-test-1
bash-4.2$ ls
1.0.1	1.0.11	1.0.14	1.0.16	1.0.18	1.0.3  1.0.5  1.0.7		  maven-metadata.xml.md5
1.0.10	1.0.13	1.0.15	1.0.17	1.0.2	1.0.4  1.0.6  maven-metadata.xml  maven-metadata.xml.sha1
bash-4.2$ 
```

**Comment by chmouel** [comment]
yeah i am more interested in the first scenario to be honest ;)

**Comment by kishansagathiya** [comment]
Content repository has been removed, thus this issue becomes irrelevant.

**Pull request closed without merging**
