### PR TITLE
Added website doc gen

### PR DESCRIPTION
**Pull request by kameshsampath**
The pipeline library steps allows to generate gh-pages based on maven profile `-Pdoc-html` and `-Pdoc-pdf`, typically replacing the fabric8 `tools/ci-docs.sh` utility.

we can then add method to `release.groovy` like 
```groovy
def documentation(project) {
  Model m = readMavenPom file: 'pom.xml'
  generateWebsiteDocs {
    project = project[0]
    releaseVersion = project[1]
    artifactId = m.artifactId
  }
}
```

Which will generate the documentation and push to `gh-pages` branch of the repo

### CODE REVIEW

**Comment by kameshsampath** [comment]
@rhuss , @rawlingsj  thoughts and comments please

**Comment by jstrachan** [comment]
might be nice to have convention; where if a specific file is present in the source code we always invoke the gneerateWebsiteDocs in a release (to avoid folks having to customise the Jenkinsfile)?

**Comment by rawlingsj** [comment]
Also we'll need to hold off merging into this repo until I've migrated all the old style shared pipelines across from my fork.  We can't merge my fork yet because the shared library isn't versioned yet so we'd be updating everyones pipelines.  

Hopefully it will be ready soon.

**Comment by kameshsampath** [comment]
@rawlingsj i will send you the PR and you can do the merge at your disposal

**Comment by rawlingsj** [comment]
Assuming this can be closed now as this is merged https://github.com/fabric8io/fabric8-pipeline-library/pull/17

**Pull request closed without merging**
