### PR TITLE
Improve maven builder setup.

### PR DESCRIPTION
**Pull request by jerboaa**
- Correct _JAVA_OPTIONS with preferred OpenJDK
  tunables.
- Set jnlp container limit to 256m as it'll use
  32 bit JDK with new options.

### CODE REVIEW

**Comment by jerboaa** [comment]
@rawlingsj Second piece to the puzzle. Just the updated settings.

**Comment by jerboaa** [comment]
@rawlingsj Eventually it would be nice to get these merged.

I've tested this on OSIO with multiple builds of the vertx, spring boot and wfswarm boosters. For the last I had some issues in maven-fabric8-plugin where it was either not able to pull the image or lost connection to the OSBS system or something. Took them as unrelated failures. How to get to a setup which works?

1. The maven-builder image gets update to use 32bit OpenJDK. See https://github.com/fabric8io-images/maven-builder/pull/21
2. Slave base image gets updated. It's a rebuild of https://github.com/openshift/jenkins/tree/master/slave-base with https://github.com/openshift/jenkins/pull/396. That's what https://hub.docker.com/r/jerboaa/fabric8-jenkins-slave-base-centos7/tags/ is.
3. Use those images together with the updated settings. See: https://github.com/fabric8io/fabric8-pipeline-library/pull/350

Hope this makes some sense. If implemented we go from memory for the builders from `1536MB` to `896MB`, thus a `41%` reduction in memory approximately.

**Comment by rawlingsj** [comment]
Awesome work thanks @jerboaa!  I'll do some testing tomorrow as we also use these on minishift / minikube which we've realised are now running very slow builds after the jenkins master opts changes.  It's not an issue, we just need to figure out a way to use different settings for different deployments.  That's easier with the pipeline library so I can try that tomorrow.

**Comment by jerboaa** [comment]
@rawlingsj I was wondering if you had a chance to look at this? Do you need anything else from our side?

**Comment by rawlingsj** [comment]
[merge]

**Pull request merged**
